language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t yishaiz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yishaiz/docker-react npm run test
  # - docker run yishaiz/docker-react npm run test -- --coverage