language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t yishaiz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yishaiz/docker-react npm run test
  # - docker run yishaiz/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react-sample"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-eu-west-1-558343010837"
  bucket_path: "docker-react-sample"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"