version: '3'
services:
  web:
    build:
      context: . # react-app
      dockerfile: Dockerfile.dev
    stdin_open: true

    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: . # react-app
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
